### ISSUE TITLE
How to access updated files?

### ISSUE THREAD

**Issue by sistakaren** [OscarXcore/twitch-mass-ban#4]
Hi!  I tried to use this tool based on the most recent release and it seemed like it was working but none of the users were actually banned in the list I used.  I see that you have updated the files four months ago, but the most recent release is from 2017.  This is probably a basic question, but how does one access the files you updated a few months back? 

Also, thanks for making this, many streamers are getting hate raids on Twitch right now, so this tool will be incredibly useful for many and I'm hoping to get it to work.  Thanks so much!

**Comment by sistakaren** [comment]
also, to clarify: I tried to manually ban some of the people on the list and they were definitely banned when I did it individually so it's not an issue of the usernames for sure, but it seems like there are some necessary updates I need to do to get it to work... thanks!

**Comment by CyanMatter** [comment]
To download the latest commit, go to [this page](https://github.com/Stapleton/twitch-mass-ban/tree/4f889ac412bccd1b8707ec3d139f0afb11f3036b), click the "Code" button and select Download ZIP in the dropdown menu

**Comment by Stapleton** [comment]
I have moved this projects code to my [GitLab](https://git.stapleton.pw/stapleton/tmbt)

When I have finished the internal rewrite, I will do some tests and make sure its all good to go before posting a release over [here](https://git.stapleton.pw/stapleton/tmbt/-/releases)
