### ISSUE TITLE
Halts banning accounts after a couple successful ones

### ISSUE THREAD

**Issue by CyanMatter** [OscarXcore/twitch-mass-ban#5]
This application banned the first 64 accounts and then processed the remaining 292812 in the list without banning them. It reported in the console it was succeeding in banning each one. However, I verified that most accounts remain unbanned after the program ran.

The specific [list](https://github.com/hackbolt/twitchbotsnbigots) I used, if it becomes of interest.

**Comment by Jarngeir** [comment]
Have found this same issue. 
Bans the first 64 accounts, but none of the remainder on my list have had any action taken, though the console reports it as complete.

**Comment by Stapleton** [comment]
This is one of the main issues that came with the application aging.

It worked awesome for a few hundred names but with lists seemingly starting to scale up to hundreds of thousands of names, then it starts to fall apart. 

Currently reworking the internals of the project with emphasis on internal queues to keep track of what names in which channels have yet to be banned, which have an api ban request sent, and which have recieved a ban event confirmation.

This will allow for accurate ban numbers, scaling for big lists, verification that a ban succeeded or not, progress tracking, processing end reports, and self limiting to stay within rate limits without sacrificing too much throughput

The project codebase has also moved to my [GitLab](https://git.stapleton.pw/stapleton/tmbt)
